### ISSUE TITLE
probGLS

### ISSUE THREAD

**Issue by samidodino** [slisovski/TheGeolocationManual#2]
Hi Simeon!
I am trying to use your code for analyzing geolocator data retrieved from Magellanic penguin that lives in Argentina and they stay at sea during winter. I have problems when I run this: 

> data$dtime     <- as.POSIXct(strptime(data[,1], format = "%H:%M:%S %d/%m/%y"),tz='UTC')
> data           <- data[!is.na(data$dtime),]
> act            <- data
> ## wet dry data column must be called 'wetdry'
> act$wetdry    <- 1-act$WetDryState
> act <- subset(act, select = c(dtime,wetdry))
> head(act)
[1] dtime  wetdry
<0 rows> (or 0-length row.names)

Nothing is selected. Do you have any idea why that happens?
Sorry, I am sure it's me, but I can't find the solution.

best

**Comment by abfleishman** [comment]
can you post the result of `head(data)`
_________________________________________
Abram B. Fleishman | Research Scientist
Conservation Metrics, Inc. <http://www.conservationmetrics.com>
UCSC Coastal Science Campus
145 McAllister Way,
Santa Cruz, CA 95060
(541)-207-2335 | abram@conservationmetrics.com

**Comment by samidodino** [comment]
I just found the solution!! I changed this: format = '% d /% m /% Y% H:% M' in the as.POSIXct function and now It´s works! 
But I have another problem now... I can´t run the prob_algorithm function because I have this error:
"Error: no land mask file found in folder"
And that´s not true, I placed it in the same folder as all the other NetCDF files...
