### ISSUE TITLE
Could not find function "mergeSites2"

### ISSUE THREAD

**Issue by Rafnuss** [slisovski/TheGeolocationManual#3]
Thanks a lot for this manual, really cool way to learn about anaylsis of geolocator.
I'm running into some issue on the `05-GeoLight.Rmd` page at line [187](https://github.com/Rafnuss/TheGeolocationManual/blob/edd6750e316ab5524d58c3474bf92b41a15adc41/05-GeoLight.Rmd#L187):

```
Error in mergeSites2(twl = twl.gl, site = cL$site, distThreshold = 500,  : 
  could not find function "mergeSites2"
```

I'm guess it could be an issue of `GeoLight` version maybe? Any advice?

**Comment by slisovski** [comment]
Did you install the CRAN version? Try with the latest version from GitHub:

```
devtools::install_github("SLisovski/GeoLight",  ref = "Version_2.01")
```

**Comment by Rafnuss** [comment]
I'm using the version 2.00 I believe. 
But I can't find the 2.01: `https://api.github.com/repos/SLisovski/GeoLight/tarball/Version_2.01` is empty. 

```
> devtools::install_github("SLisovski/GeoLight",  ref = "Version_2.01")
Downloading GitHub repo SLisovski/GeoLight@Version_2.01
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/SLisovski/GeoLight/tarball/Version_2.01'
```

**Comment by slisovski** [comment]
Sorry it is:

```
devtools::install_github("SLisovski/GeoLight",  ref = "Update_2.01")
```

**Comment by Rafnuss** [comment]
Perfect, that solved my problem! 
Thanks
